# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.19

# Default target executed when no arguments are given to make.
default_target: all

.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:


#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:


# Disable VCS-based implicit rules.
% : %,v


# Disable VCS-based implicit rules.
% : RCS/%


# Disable VCS-based implicit rules.
% : RCS/%,v


# Disable VCS-based implicit rules.
% : SCCS/s.%


# Disable VCS-based implicit rules.
% : s.%


.SUFFIXES: .hpux_make_needs_suffix_list


# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

#Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:

.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/local/Cellar/cmake/3.19.3/bin/cmake

# The command to remove a file.
RM = /usr/local/Cellar/cmake/3.19.3/bin/cmake -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = "/Users/angelocarlino/models/RICE50++ copy"

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = "/Users/angelocarlino/models/RICE50++ copy"

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/local/Cellar/cmake/3.19.3/bin/cmake --regenerate-during-build -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache

.PHONY : rebuild_cache/fast

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake cache editor..."
	/usr/local/Cellar/cmake/3.15.4/bin/ccmake -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache

.PHONY : edit_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start "/Users/angelocarlino/models/RICE50++ copy/CMakeFiles" "/Users/angelocarlino/models/RICE50++ copy//CMakeFiles/progress.marks"
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start "/Users/angelocarlino/models/RICE50++ copy/CMakeFiles" 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean

.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named RICE

# Build rule for target.
RICE: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 RICE
.PHONY : RICE

# fast build rule for target.
RICE/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/RICE.dir/build.make CMakeFiles/RICE.dir/build
.PHONY : RICE/fast

src/RICE.o: src/RICE.cpp.o

.PHONY : src/RICE.o

# target to build an object file
src/RICE.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/RICE.dir/build.make CMakeFiles/RICE.dir/src/RICE.cpp.o
.PHONY : src/RICE.cpp.o

src/RICE.i: src/RICE.cpp.i

.PHONY : src/RICE.i

# target to preprocess a source file
src/RICE.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/RICE.dir/build.make CMakeFiles/RICE.dir/src/RICE.cpp.i
.PHONY : src/RICE.cpp.i

src/RICE.s: src/RICE.cpp.s

.PHONY : src/RICE.s

# target to generate assembly for a file
src/RICE.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/RICE.dir/build.make CMakeFiles/RICE.dir/src/RICE.cpp.s
.PHONY : src/RICE.cpp.s

src/RICEMain.o: src/RICEMain.cpp.o

.PHONY : src/RICEMain.o

# target to build an object file
src/RICEMain.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/RICE.dir/build.make CMakeFiles/RICE.dir/src/RICEMain.cpp.o
.PHONY : src/RICEMain.cpp.o

src/RICEMain.i: src/RICEMain.cpp.i

.PHONY : src/RICEMain.i

# target to preprocess a source file
src/RICEMain.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/RICE.dir/build.make CMakeFiles/RICE.dir/src/RICEMain.cpp.i
.PHONY : src/RICEMain.cpp.i

src/RICEMain.s: src/RICEMain.cpp.s

.PHONY : src/RICEMain.s

# target to generate assembly for a file
src/RICEMain.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/RICE.dir/build.make CMakeFiles/RICE.dir/src/RICEMain.cpp.s
.PHONY : src/RICEMain.cpp.s

src/carbon/Carbon.o: src/carbon/Carbon.cpp.o

.PHONY : src/carbon/Carbon.o

# target to build an object file
src/carbon/Carbon.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/RICE.dir/build.make CMakeFiles/RICE.dir/src/carbon/Carbon.cpp.o
.PHONY : src/carbon/Carbon.cpp.o

src/carbon/Carbon.i: src/carbon/Carbon.cpp.i

.PHONY : src/carbon/Carbon.i

# target to preprocess a source file
src/carbon/Carbon.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/RICE.dir/build.make CMakeFiles/RICE.dir/src/carbon/Carbon.cpp.i
.PHONY : src/carbon/Carbon.cpp.i

src/carbon/Carbon.s: src/carbon/Carbon.cpp.s

.PHONY : src/carbon/Carbon.s

# target to generate assembly for a file
src/carbon/Carbon.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/RICE.dir/build.make CMakeFiles/RICE.dir/src/carbon/Carbon.cpp.s
.PHONY : src/carbon/Carbon.cpp.s

src/climate/Climate.o: src/climate/Climate.cpp.o

.PHONY : src/climate/Climate.o

# target to build an object file
src/climate/Climate.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/RICE.dir/build.make CMakeFiles/RICE.dir/src/climate/Climate.cpp.o
.PHONY : src/climate/Climate.cpp.o

src/climate/Climate.i: src/climate/Climate.cpp.i

.PHONY : src/climate/Climate.i

# target to preprocess a source file
src/climate/Climate.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/RICE.dir/build.make CMakeFiles/RICE.dir/src/climate/Climate.cpp.i
.PHONY : src/climate/Climate.cpp.i

src/climate/Climate.s: src/climate/Climate.cpp.s

.PHONY : src/climate/Climate.s

# target to generate assembly for a file
src/climate/Climate.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/RICE.dir/build.make CMakeFiles/RICE.dir/src/climate/Climate.cpp.s
.PHONY : src/climate/Climate.cpp.s

src/economy/Econ.o: src/economy/Econ.cpp.o

.PHONY : src/economy/Econ.o

# target to build an object file
src/economy/Econ.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/RICE.dir/build.make CMakeFiles/RICE.dir/src/economy/Econ.cpp.o
.PHONY : src/economy/Econ.cpp.o

src/economy/Econ.i: src/economy/Econ.cpp.i

.PHONY : src/economy/Econ.i

# target to preprocess a source file
src/economy/Econ.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/RICE.dir/build.make CMakeFiles/RICE.dir/src/economy/Econ.cpp.i
.PHONY : src/economy/Econ.cpp.i

src/economy/Econ.s: src/economy/Econ.cpp.s

.PHONY : src/economy/Econ.s

# target to generate assembly for a file
src/economy/Econ.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/RICE.dir/build.make CMakeFiles/RICE.dir/src/economy/Econ.cpp.s
.PHONY : src/economy/Econ.cpp.s

src/economy/EconAgent.o: src/economy/EconAgent.cpp.o

.PHONY : src/economy/EconAgent.o

# target to build an object file
src/economy/EconAgent.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/RICE.dir/build.make CMakeFiles/RICE.dir/src/economy/EconAgent.cpp.o
.PHONY : src/economy/EconAgent.cpp.o

src/economy/EconAgent.i: src/economy/EconAgent.cpp.i

.PHONY : src/economy/EconAgent.i

# target to preprocess a source file
src/economy/EconAgent.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/RICE.dir/build.make CMakeFiles/RICE.dir/src/economy/EconAgent.cpp.i
.PHONY : src/economy/EconAgent.cpp.i

src/economy/EconAgent.s: src/economy/EconAgent.cpp.s

.PHONY : src/economy/EconAgent.s

# target to generate assembly for a file
src/economy/EconAgent.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/RICE.dir/build.make CMakeFiles/RICE.dir/src/economy/EconAgent.cpp.s
.PHONY : src/economy/EconAgent.cpp.s

src/emodps/moeaframework.o: src/emodps/moeaframework.c.o

.PHONY : src/emodps/moeaframework.o

# target to build an object file
src/emodps/moeaframework.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/RICE.dir/build.make CMakeFiles/RICE.dir/src/emodps/moeaframework.c.o
.PHONY : src/emodps/moeaframework.c.o

src/emodps/moeaframework.i: src/emodps/moeaframework.c.i

.PHONY : src/emodps/moeaframework.i

# target to preprocess a source file
src/emodps/moeaframework.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/RICE.dir/build.make CMakeFiles/RICE.dir/src/emodps/moeaframework.c.i
.PHONY : src/emodps/moeaframework.c.i

src/emodps/moeaframework.s: src/emodps/moeaframework.c.s

.PHONY : src/emodps/moeaframework.s

# target to generate assembly for a file
src/emodps/moeaframework.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/RICE.dir/build.make CMakeFiles/RICE.dir/src/emodps/moeaframework.c.s
.PHONY : src/emodps/moeaframework.c.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... RICE"
	@echo "... src/RICE.o"
	@echo "... src/RICE.i"
	@echo "... src/RICE.s"
	@echo "... src/RICEMain.o"
	@echo "... src/RICEMain.i"
	@echo "... src/RICEMain.s"
	@echo "... src/carbon/Carbon.o"
	@echo "... src/carbon/Carbon.i"
	@echo "... src/carbon/Carbon.s"
	@echo "... src/climate/Climate.o"
	@echo "... src/climate/Climate.i"
	@echo "... src/climate/Climate.s"
	@echo "... src/economy/Econ.o"
	@echo "... src/economy/Econ.i"
	@echo "... src/economy/Econ.s"
	@echo "... src/economy/EconAgent.o"
	@echo "... src/economy/EconAgent.i"
	@echo "... src/economy/EconAgent.s"
	@echo "... src/emodps/moeaframework.o"
	@echo "... src/emodps/moeaframework.i"
	@echo "... src/emodps/moeaframework.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

